development:
  adapter: postgresql
  encoding: unicode
  database: soobooki_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: soobooki_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: soobooki_production
  pool: 5
  username: hong
  password: hong10
